Repository cloudposse/terraform-opsgenie-incident-management, pull requests merged in 2024-07, with the labels that each got.

#64 Update .github/settings.yml
  .github/auto-release.yml
  .github/settings.yml
Labels: auto-update, no-release, migration

#65 update test cases
  examples/advanced_features/api_integration.tf
  examples/advanced_features/integration_action.tf
  examples/advanced_features/team.tf
  examples/alert_policy/main.tf
  examples/api_integration/fixtures.tfvars
  examples/api_integration/main.tf
  examples/complete/api_integration.tf
  examples/complete/escalation.tf
  examples/complete/fixtures.tfvars
  examples/complete/service.tf
  examples/complete/service_incident_rule.tf
  examples/complete/team.tf
  examples/complete/team_routing_rule.tf
  examples/complete/user.tf
  examples/config/main.tf
  examples/escalation/main.tf
  examples/integration_action/main.tf
  examples/notification_policy/main.tf
  examples/schedule/main.tf
  examples/team/main.tf
  examples/team_routing_rule/main.tf
  examples/user/main.tf
  main.tf
  test/src/examples_advanced_features.go
  test/src/examples_alert_policy_test.go
  test/src/examples_api_integration_test.go
  test/src/examples_complete_test.go
  test/src/examples_config_test.go
  test/src/examples_escalation_test.go
  test/src/examples_integration_action.go
  test/src/examples_notification_policy_test.go
  test/src/examples_team_routing_rule_test.go
  test/src/examples_team_test.go
  test/src/examples_user_test.go
  test/src/go.mod
  test/src/go.sum
  test/src/utils.go
Labels: triage

#76 [Tests] Update GHA to run all tests
  examples/advanced_features/fixtures.tfvars
  examples/alert_policy/fixtures.tfvars
  examples/config/fixtures.tfvars
  examples/config/resources/escalations.yaml
  examples/config/resources/notification_policies.yaml
  examples/config/resources/schedule_rotations.yaml
  examples/config/resources/schedules.yaml
  examples/config/resources/users.yaml
  examples/escalation/fixtures.tfvars
  examples/escalation/main.tf
  examples/integration_action/fixtures.tfvars
  examples/notification_policy/fixtures.de_duplication_action.tfvars
  examples/notification_policy/fixtures.delay_action.tfvars
  examples/notification_policy/fixtures.tfvars
  examples/notification_policy/main.tf
  examples/notification_policy/variables.tf
  examples/schedule/fixtures.tfvars
  examples/schedule/main.tf
  examples/team/fixtures.tfvars
  examples/team_routing_rule/fixtures.tfvars
  examples/team_routing_rule/main.tf
  examples/user/fixtures.tfvars
  examples/user/main.tf
  examples/user/variables.tf
  modules/config/escalations.tf
  modules/notification_policy/main.tf
  test/Makefile
  test/src/Makefile
  test/src/examples_alert_policy_test.go
  test/src/examples_api_integration_test.go
  test/src/examples_config_test.go
  test/src/examples_escalation_test.go
  test/src/examples_notification_policy_test.go
  test/src/examples_team_routing_rule_test.go
  test/src/examples_team_test.go
  test/src/examples_user_test.go
Labels: needs-cloudposse

#60 [Existing Resources] Add Team and Schedule
  modules/config/README.md
  modules/config/alert_policies.tf
  modules/config/api_integrations.tf
  modules/config/escalations.tf
  modules/config/existing_resources.tf
  modules/config/existing_users.tf
  modules/config/main.tf
  modules/config/notification_policies.tf
  modules/config/schedule_rotations.tf
  modules/config/schedules.tf
  modules/config/services.tf
  modules/config/team_routing_rules.tf
Labels: triage
